import random

notes = [
    "Our actions may be impeded...but there can be no empeding our intentions or dispositions. Because we can accomodate and adapt. The mind adapts and converts to its own purposes the ostacle to our acting.\n",
    "The impediment to action advances action.\nWhat stands in the way becomes the way.\n",
    "Bad companies are destroyed by crisis. Good companies survive them. Great companies are improved by them.\n",
    "The obstacle in the path becomes the path. Never forget, within every obstacle is an opportunity to improve our condition. (Under the rock)\n",
    "The things which hurt, instruct - Benjamin Franklin\n",
    "Overcoming obstacles is a discipline of three critical steps.\nIt begins with how we look at our specific problems, our attitude or approach; then the energy and creativity with which we actively break them down and turn them into opportunities; finally, the cultivation and maintenance of an inner will that allows us to handle defeat and difficulty.\n",
    "To prevent becoming overwhelmed by the world around us, we must, as the ancients practiced, learn how to limit our passions and their control over our lives.\nWhile others are excited or afraid, we will remain calm and imperturbable.\nWe will see things simply and straightforwardly, as they truly are -neither good or bad.\n",
    "Be fearful when others are greedy and greedy when others are fearful. - Rockefeller\n",
    "Humans are still primed to detect threats and dangers that no longer exist\n",
    "Choose not to be harmed--and you won't feel harmed.\nDon't feel harmed--and you haven't been.\n-Marcus Aurelius\n",
    "Be objective. Focus on what can be controlled.\n",
    "This can't harm me--I might not have wanted it to happen, but I decide how it will affect me. No one else has the right.\nWe are never completely powerless.\n",
    "Nothing is either good or bad, but thinking makes it so. -Shakespeare\n",
    "Just because your mind tells you that something is awful or evil or unplanned or otherwise negative doesn't mean you have to agree. We decide what story to tell ourselves. Or whether we will tell one at all.\n",
    "What such a man needs is not courage but nerve control, cool headedness. This he can get only by practice. -Theodore Roosevelt\n",
    "Greek word: apatheia = kind of calm equanimity that comes with the absence of irrational or extreme emotions.\n",
    "When you worry, ask yourself, 'What am I choosing to not see right now?' What important things are you missing because you chose worry over introspection, alertness or wisdom? - Gavin de Becker\n",
    "I am not going to die from this. I am not going to die from this.\nDo I need to freak out about this ?\n",
    "Don't let the force of an impression when it first hit you knock you off your feet; just say to it: Hold on a moment; let me see who you are and what you represent. Let me put you to the test. -Epictetus\n",
    "The perceving eye is weak, the observing eye is strong.\n",
    "Give yourself clarity, not sympathy.\n",
    "The task, as Pericles showed, is not to ignore fear but to explain it away.\n",
    "Where the head goes, the body follows. Perception precedes action. Right action follows the right perspective.\n",
    "In life, our first job is this, to divide and distinguish things into two categories; externals I cannot control, but the choices I make with regard to them I do control. Where will I find good and bad? In me, in my choices. -Epictetus\n",
    "Focus on the moment, not the monsters that may or may not be up ahead.\n",
    "Remember that this moment is not your life, it's just a moment in your life.\n",
    "There is good in everything, if only we look for it.\n",
    "It's our preconceptions that are the problem. They tell us that things should or need to be a certain way, so when they're not, we naturally assume that we are at disadvantage or that we'd be wasting our time to pursue an alternate course. When really, it's all fair game, and every situation is an opportunity for us to act.\n",
    "Well you had a hypothesis and it turned out to be wrong. Why should that upset you ? It wouldn't piss off a scientist, it would help him.\n",
    "We must all either wear out or rust out, every one of us. My choice is to wear out. -Theodore Roosevelt\n",
    "Stay moving, always. Courage = taking actions\n",
    "We will not be stopped by failure, we will not be rushed or distracted by external noise.\n",
    "In fact, it was the slow pressure, repeated from many different angles, the elimination of so many other primising options, that slowly and surely churned the solution to the top of the pile.\n",
    "Because when you play all the way to the whistle, there's no reason to worry about the clock. You know you won't stop until it's over--that every second available is yours to use. So temporary setbacks aren't discouraging. They are just bumps along a road that you intend to travel all the way down.\n",
    "It's okay to be discouraged, it's not okay to quit.\n",
    "The first step is an intuition--and comes with a burst--then difficulties arise. -Edison\n",
    "Energy is an asset we can always find more of. It's a renewable ressource.\n",
    "Iterating, failing, improving.\n",
    "Failure shows us the way, by showing us what isn't the way.\n",
    "Something difficult: Break it down into pieces. Simply do what you need to do right now. And do it well. And then move on to the next thing. Follow the process and not the prize.\nExcellence is a matter of step.\n",
    "Being trapped is just a position, not a fate. You get out of it by addressing and eliminating each part of that position through small, deliberate actions.\n",
    "The process is about doing the right things, right now. Not worrying about what might happen later, or the results or the whole picture.\n",
    "'What is the meaning of life?' The world is asking you that question. And it's your job to answer with your actions.\nOur job is simply to answer well.\n",
    "What's right is what works. Forget the rule book, settle the issue.\n'I dont' care if the cat is black or white, so long as it catches mice.' -Deng Xiaoping\n",
    "Think progress, not perfection.\n",
    "Sometimes, the longest way around is the shortest way home.\n",
    "Nothing can ever prevent us from trying. Ever.\n",
    "We must be willing to roll the dice and lose. Prepare, at the end of the day, for none of it to work.\n",
    "Will has a lot more to do with surrender than with strength. The will is the one thing we control completely, always.\n",
    "This too shall pass. -Lincoln\n",
    "One needs only to look at history to see how random and vicious and awful the world can be. The incomprehensible happens all the time.\nCertain things in life will cut you open like a knife. When that happens--at that exposing moment--the world gets a glimpse of what's truly inside you. So what will be revealed when you're sliced opend by tension and pressure ? Iron? Air? Or bullshit?\n",
    "We craft our spiritual strength through physical exercise, and our physical hardiness through mental practice.\n",
    "During the good times, we strengthen ourselves and our bodies so that during the difficult times, we can depend on it.\n",
    "premeditatio malorum = premeditation of evils\n",
    "Manage expectations. Because sometimes the only answer to 'What if ?' is, It will suck but we'll be okay.\n",
    "The only guarantee ever is that things will go wrong.\n",
    "You know what's better than building things up in your imagination? Building things up in real life. Chimeras are like bandages--they only hurt when torn away.\n",
    "With anticipation, we can endure.\n",
    "There is always someone or something that could change the plan.\n",
    "Follow where the events take you, like water rolling down a hill--it always gets to the bottom eventually, doesn't it?\n",
    "As Francis Bacon once said, nature, in order to be commanded, must be obeyed.\n",
    "We don't get to choose what happens to us, but we can always choose how we feel about it.\n",
    "Stop pretending that what you're going through is somehow special or unfair. Whatever trouble you're having--no matter how difficult--is not some unique misfortune picked out especially for you. It just is what it is.\n",
    "Memento mori.\nRemember you are mortal.\n",
    "Haitian proverb: Behind mountains are more mountains.\n",
    "Life is a marathon, not a sprint. Conserve your energy.\n",
    "See things for what they are.\nDo what we can.\nEndure and bear what we must.\n",
]

alea = random.randint(0,66)

nb = input("Choose one between 0 and 66\n")

if nb>66:
    nb = alea

print notes[nb]
